###############################################################################
# Generated By: generate.py
# User: -
# Date: -
###############################################################################

from pinaht.knowledge.types.knowledge import Knowledge  # noqa F401


from pinaht.knowledge.types.password import Password

from pinaht.knowledge.types.name import Name


class Credentials(Knowledge):
    """
    Holds unmatched usernames and passwords.
    """

    def __init__(self, *args, **kwargs):
        """
        Constructor of the class Credentials.
        """

        super().__init__()
        self.init_credentials(*args)

        self.passwords = []

        self.users = []

        self.type = "BRANCH"
        self.lookup = {"passwords": self.passwords, "users": self.users}

        for key, item in kwargs.items():
            if isinstance(item, list):
                for element in item:
                    self.add_child(key, element)
            else:
                self.add_child(key, item)

    def __str__(self):
        return self.__class__.__name__

    def fuzzy_eq(self, other) -> float:
        # TODO
        if id(self) == id(other):
            return 1.0
        if not type(self) == type(other):
            return 0.0
        return 0.5

    def add_child(self, key, child):
        if key not in self.lookup:
            raise ValueError(
                f"Type 'Credentials' has no child/attribute with name {key}. "
                "Check types.yaml or the generated PDF for correct identifiers."
            )

        if key == "passwords" and isinstance(child, Password):
            self.passwords.append(child)
            child.parent = self

        elif key == "users" and isinstance(child, Name):
            self.users.append(child)
            child.parent = self

        else:
            raise TypeError(f"Child for attribute {key} is not of the right type")

    def init_credentials(self, *args):  # noqa F811
        pass

    ### USER DEFINED METHODS ### # noqa: E266
