###############################################################################
# Generated By: generate.py
# User: -
# Date: -
###############################################################################

from pinaht.knowledge.types.knowledge import Knowledge  # noqa F401


from pinaht.knowledge.types.ipaddress import IPAddress

from pinaht.knowledge.types.executable import Executable


class LocalHost(Knowledge):
    """
        Describes an Object of the Type LocalHost.
    A LocalHost describes knowledge about the computer the program is running on.
    """

    def __init__(self, *args, **kwargs):
        """
        Constructor of the class LocalHost.
        """

        super().__init__()
        self.init_localhost(*args)

        self.address = []

        self.executable = []

        self.type = "BRANCH"
        self.lookup = {"address": self.address, "executable": self.executable}

        for key, item in kwargs.items():
            if isinstance(item, list):
                for element in item:
                    self.add_child(key, element)
            else:
                self.add_child(key, item)

    def __str__(self):
        return self.__class__.__name__

    def fuzzy_eq(self, other) -> float:
        # TODO
        if id(self) == id(other):
            return 1.0
        if not type(self) == type(other):
            return 0.0
        return 0.5

    def add_child(self, key, child):
        if key not in self.lookup:
            raise ValueError(
                f"Type 'LocalHost' has no child/attribute with name {key}. "
                "Check types.yaml or the generated PDF for correct identifiers."
            )

        if key == "address" and isinstance(child, IPAddress):
            self.address.append(child)
            child.parent = self

        elif key == "executable" and isinstance(child, Executable):
            self.executable.append(child)
            child.parent = self

        else:
            raise TypeError(f"Child for attribute {key} is not of the right type")

    def init_localhost(self, *args):  # noqa F811
        pass

    ### USER DEFINED METHODS ### # noqa: E266
