###############################################################################
# Generated By: generate.py
# User: -
# Date: -
###############################################################################

from pinaht.knowledge.types.knowledge import Knowledge  # noqa F401


from pinaht.knowledge.types.fstree import FsTree


class LocalFsTree(FsTree):
    """
    Tree structure mirroring a local filesystem
    """

    def __init__(self, *args, **kwargs):
        """
        Constructor of the class LocalFsTree.
        """

        super().__init__()
        self.init_localfstree(*args)

        self.type = "LEAF_CUSTOM"
        self.lookup = {}

        for key, item in kwargs.items():
            if isinstance(item, list):
                for element in item:
                    self.add_child(key, element)
            else:
                self.add_child(key, item)

    def fuzzy_eq(self, other) -> float:
        # TODO
        if id(self) == id(other):
            return 1.0
        if not type(self) == type(other):
            return 0.0
        return 0.5

    def add_child(self, key, child):
        if key not in self.lookup:
            raise ValueError(
                f"Type 'LocalFsTree' has no child/attribute with name {key}. "
                "Check types.yaml or the generated PDF for correct identifiers."
            )

        else:
            raise TypeError(f"Child for attribute {key} is not of the right type")

    def init_localfstree(self, *args):  # noqa F811
        pass

    ### USER DEFINED METHODS ### # noqa: E266

    def init_localfstree(self, *args):  # noqa F811
        self.filesystem = args[0]
        self.shell = args[1]
