###############################################################################
# Generated By: generate.py
# User: -
# Date: -
###############################################################################

from pinaht.knowledge.types.knowledge import Knowledge  # noqa F401


from pinaht.knowledge.types.name import Name

from pinaht.knowledge.types.password import Password


class LoginUser(Knowledge):
    """
    Describes an Object of the Type User.
    """

    def __init__(self, *args, **kwargs):
        """
        Constructor of the class LoginUser.
        """

        super().__init__()
        self.init_loginuser(*args)

        self.name = []

        self.password = []

        self.type = "BRANCH"
        self.lookup = {"name": self.name, "password": self.password}

        for key, item in kwargs.items():
            if isinstance(item, list):
                for element in item:
                    self.add_child(key, element)
            else:
                self.add_child(key, item)

    def __str__(self):
        return self.__class__.__name__

    def fuzzy_eq(self, other) -> float:
        # TODO
        if id(self) == id(other):
            return 1.0
        if not type(self) == type(other):
            return 0.0
        return 0.5

    def add_child(self, key, child):
        if key not in self.lookup:
            raise ValueError(
                f"Type 'LoginUser' has no child/attribute with name {key}. "
                "Check types.yaml or the generated PDF for correct identifiers."
            )

        if key == "name" and isinstance(child, Name):
            self.name.append(child)
            child.parent = self

        elif key == "password" and isinstance(child, Password):
            self.password.append(child)
            child.parent = self

        else:
            raise TypeError(f"Child for attribute {key} is not of the right type")

    def init_loginuser(self, *args):  # noqa F811
        pass

    ### USER DEFINED METHODS ### # noqa: E266
