###############################################################################
# Generated By: generate.py
# User: -
# Date: -
###############################################################################

from pinaht.knowledge.types.knowledge import Knowledge  # noqa F401


from pinaht.knowledge.types.operatingsystemtype import OperatingSystemType

from pinaht.knowledge.types.version import Version


class OS(Knowledge):
    """
    Describes an Object of the Type OS.
    """

    def __init__(self, *args, **kwargs):
        """
        Constructor of the class OS.
        """

        super().__init__()
        self.init_os(*args)

        self.os_type = []

        self.expected_version = []

        self.type = "BRANCH"
        self.lookup = {"os_type": self.os_type, "expected_version": self.expected_version}

        for key, item in kwargs.items():
            if isinstance(item, list):
                for element in item:
                    self.add_child(key, element)
            else:
                self.add_child(key, item)

    def __str__(self):
        return self.__class__.__name__

    def fuzzy_eq(self, other) -> float:
        # TODO
        if id(self) == id(other):
            return 1.0
        if not type(self) == type(other):
            return 0.0
        return 0.5

    def add_child(self, key, child):
        if key not in self.lookup:
            raise ValueError(
                f"Type 'OS' has no child/attribute with name {key}. "
                "Check types.yaml or the generated PDF for correct identifiers."
            )

        if key == "os_type" and isinstance(child, OperatingSystemType):
            self.os_type.append(child)
            child.parent = self

        elif key == "expected_version" and isinstance(child, Version):
            self.expected_version.append(child)
            child.parent = self

        else:
            raise TypeError(f"Child for attribute {key} is not of the right type")

    def init_os(self, *args):  # noqa F811
        pass

    ### USER DEFINED METHODS ### # noqa: E266
