###############################################################################
# Generated By: generate.py
# User: -
# Date: -
###############################################################################

from pinaht.knowledge.types.knowledge import Knowledge  # noqa F401


from pinaht.knowledge.types.name import Name

from pinaht.knowledge.types.text import Text


class ScriptElement(Knowledge):
    """
    A Element of a script result
    """

    def __init__(self, *args, **kwargs):
        """
        Constructor of the class ScriptElement.
        """

        super().__init__()
        self.init_scriptelement(*args)

        self.id = []

        self.output = []

        self.type = "BRANCH"
        self.lookup = {"id": self.id, "output": self.output}

        for key, item in kwargs.items():
            if isinstance(item, list):
                for element in item:
                    self.add_child(key, element)
            else:
                self.add_child(key, item)

    def __str__(self):
        return self.__class__.__name__

    def fuzzy_eq(self, other) -> float:
        # TODO
        if id(self) == id(other):
            return 1.0
        if not type(self) == type(other):
            return 0.0
        return 0.5

    def add_child(self, key, child):
        if key not in self.lookup:
            raise ValueError(
                f"Type 'ScriptElement' has no child/attribute with name {key}. "
                "Check types.yaml or the generated PDF for correct identifiers."
            )

        if key == "id" and isinstance(child, Name):
            self.id.append(child)
            child.parent = self

        elif key == "output" and isinstance(child, Text):
            self.output.append(child)
            child.parent = self

        else:
            raise TypeError(f"Child for attribute {key} is not of the right type")

    def init_scriptelement(self, *args):  # noqa F811
        pass

    ### USER DEFINED METHODS ### # noqa: E266
