###############################################################################
# Generated By: generate.py
# User: -
# Date: -
###############################################################################

from pinaht.knowledge.types.knowledge import Knowledge, KnowledgeEnumMeta  # noqa F401

from enum import Enum


class Transport(Knowledge, Enum, metaclass=KnowledgeEnumMeta):
    """
    a ENUM over the Transport Protocol (OSI Layer 4)
    """

    TCP = 1

    UDP = 2

    SCTP = 3

    TLS = 4

    DTLS = 5

    def __init__(self, *args, **kwargs):
        """
        Constructor of the class Transport.
        """

        super().__init__()
        self.init_transport(*args)

        self.type = "LEAF_ENUM"
        self.lookup = {}

        for key, item in kwargs.items():
            if isinstance(item, list):
                for element in item:
                    self.add_child(key, element)
            else:
                self.add_child(key, item)

    def __str__(self):
        return self.name

    def fuzzy_eq(self, other) -> float:
        if type(self) == type(other):
            if self == other:
                return 1.0
        return 0.0

    def add_child(self, key, child):
        if key not in self.lookup:
            raise ValueError(
                f"Type 'Transport' has no child/attribute with name {key}. "
                "Check types.yaml or the generated PDF for correct identifiers."
            )

        else:
            raise TypeError(f"Child for attribute {key} is not of the right type")

    def init_transport(self, *args):  # noqa F811
        pass

    ### USER DEFINED METHODS ### # noqa: E266
